### ISSUE TITLE
Runtimes are rounded to integer

### ISSUE THREAD

**Issue by JonasHanselle** [fmohr/lccv#10]
Runtimes in the DataFrame returned by LCCV are integers.

**Comment by JonasHanselle** [comment]
This might be caused by https://github.com/fmohr/lccv/blob/32fbe3e6ac034fff18df78f47d94966c614391ad/python/lccv/lccv.py#L151 but it also happens when I'm using a custom evaluator for LCCV and thus custom runtimes.

**Comment by fmohr** [comment]
thanks for this remark. It has been resolved in the last release.
